runtime: nodejs10
env: standard
instance_class: F1
handlers:
  - url: /
    static_files: www/index.html
    require_matching_file: false
    upload: www/index.html
  - url: /(.*)
    static_files: js/\1
    require_matching_file: false
    upload: js/(.*)
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
